import { Typography, Container } from '@mui/material';
import PageTitle from '@components/PageTitle';

const Terms = () => {
  return (
    <>
        <Container maxWidth="760px" sx={{ maxWidth: '760px', mx: 'auto' }}>
            <PageTitle 
                title="Terms and Conditions"
            />

            <Typography variant="h4">
                ErgoPad Dao
            </Typography>

            <Typography variant="h5">
                Terms and Conditions of https://ergopad.io
            </Typography>

            <Typography variant="p">
                Last revised Date: 20th November, 2021
            </Typography>

            <Typography variant="h6">
                1. Introduction
            </Typography>
            
            <Typography variant="p">
                These Terms and Conditions (herein referred to as &quot;Terms&quot;) govern the use and the conditions of https://ergopad.io (herein referred as &quot;Website&quot;), and the Services provided by the ErgoPad DAO (herein referred to as &quot;Company&quot; or &quot;We&quot; or &quot;Us&quot;), a Decentralized Autonomous Organization that is controlled by various token holders around the globe. These Terms constitute a binding and enforceable legal contract between the Company and its Affiliate and subsidiaries worldwide and you, an end user of the Services (herein referred to as &quot;You&quot; or &quot;User&quot;) in relation to the Services. You and the Company are referred to separately as &quot;Party&quot; and collectively as &quot;Parties&quot;.
            </Typography> 

            <Typography variant="p">
                By accessing, registering, using, or clicking on the Services, and information made available by the Company via the Website, you hereby accept and agree to all the Terms set forth herein.
            </Typography>

            <Typography variant="p">
                By using the Website and the Services in any capacity, you agree that: (i) You have read and familiarized yourself with these Terms; (ii) You understand these Terms; and (iii) You agree to be bound by these Terms when using the Website. If You do not agree to these Terms, please do not access or use the Website and the Services.
            </Typography>

            <Typography variant="p">
                We reserve the right to modify or amend these Terms, the Website, or any content on either one of the platforms from time to time, including for security, legal, or regulatory reasons, as well as to reflect updates or changes to the services or functionality of the Website. You are advised to check these Terms periodically to ensure that you are cognizant of the current versions and comply with them. Users of the Website and the Services are bound by these changes which will take immediate effect after the revised versions of these Terms have been published on the Website or the relevant mobile application. Through your continued use of or interaction with the Website, the Services, tools, and information made available on these platforms, you hereby agree to be bound by the provisions highlighted in the subsequent versions.
            </Typography>

            <Typography variant="p">
                By accessing, registering, using, or clicking on the Services, and information made available by the Company via the Website, you hereby accept and agree to all the Terms set forth herein.
            </Typography>

            <Typography variant="h6">
                2. Definitions
            </Typography>

            <Typography variant="p">
                <b>&quot;Affiliate&quot;</b> means, in relation to a person, any company or other entity, whether or not with legal personality, which directly or indirectly controls, is controlled by or is under joint control with that person. For this purpose, a person is deemed to control a company or entity if it (a) owns, directly or indirectly, at least 50 percent of the capital of the other company, or (b) in the absence of such ownership interest, substantially has the power to direct or cause the direction of the management and set the policies of such company or entity.
            </Typography>

            <Typography variant="p">
                <b>&quot;Applicable Laws&quot;</b> refers to acts, statutes, regulations, ordinances, treaties, guidelines, and policies issued by governmental organizations or regulatory bodies relevant to a certain party. 
            </Typography>

            <Typography variant="p">
                <b>&quot;Content&quot;</b> refers to all content generated by the Company, including logos, identifying marks, images, illustrations, designs, icons, photographs, videos, text, any written or multimedia materials, services, advertisements, software, code, data, files, archives, folders, or available downloads on the ErgoPad Platform.
            </Typography>

            <Typography variant="p">
                <b>&quot;IDO&quot;</b> refers to Initial DEX Offerings or Initial Decentralized Exchange Offerings.
            </Typography>

            <Typography variant="p">
                <b>&quot;Platform&quot;</b> refers to the collective smart contracts deployed by the Company on the Ergo platform. They run separate from this Website and the operator of this Website has no control of these smart contracts. 
            </Typography>

            <Typography variant="p">
                <b>&quot;Project&quot;</b> refers to any project being launched in an Initial Decentralized Offering (&apos;IDO&apos;) event on the ErgoPad Platform.
            </Typography>

            <Typography variant="p">
                <b>&quot;Services&quot;</b> refer to the services provided to the Users through the Website, which include the accessibility to the new IDO token offered from each IDO fundraising project, staking service and other relevant services available through the Platform and all free trials and beta services made available by the Company, which may be subject to periodic revision.
            </Typography>

            <Typography variant="p">
                <b>&quot;Staking or Stake&quot;</b> refers to the staking or deposit service in which the Users can delegate or deposit the User&apos;s ErgoPad Tokens in exchange for a share of staking rewards on the Platform.
            </Typography>

            <Typography variant="p">
                <b>&quot;Token&quot;</b> refers to a blockchain-based token which is issued, stored, transferred, transacted on the Ergo network. Users need to hold ErgoPad Tokens to participate in any Services on the Platform including Staking or pre-sale of Project selected for the launchpad.
            </Typography>

            <Typography variant="p">
                <b>&quot;User&quot;</b> refers to any third party interacting with this Website, the Services offered by the Company, or the ErgoPad Platform operating on the Ergo blockchain. 
            </Typography>
            
            <Typography variant="p">
                <b>&quot;Wallet(s)&quot;</b> refers to a wallet which must be compatible with the Ergo network.
            </Typography>

            <Typography variant="p">
                <b>&quot;Website&quot;</b> refers to this website, https://ergopad.io
            </Typography>

            <Typography variant="h6">
                3. General Provisions
            </Typography>

            <Typography variant="p">
                1. Contractual Relationship: These Terms constitute a valid and binding agreement between You and the Company. The binding obligations stipulated in these Terms are enforceable.
           </Typography>

            <Typography variant="p">
                2. Revision and Amendments: The Company reserves the right to revise, amend, or update any clauses and provisions stipulated in these Terms in its sole discretion at any time. The Company will notify the revision or amendment of such clauses or provisions by updating these Terms and specify the &apos;Last Revised Date&apos; displayed on a page of Terms and Conditions. Any revisions and updates on these Terms will be automatically effective upon their publication on the Website. Therefore, your continuity of accessing or using the ErgoPad Platform through this Website, and/or any other Services will be deemed that you agree to have read, understood, and accepted all revised terms and provisions. If you do not agree on any revised or updated terms and provisions, you should immediately stop accessing the Website or using the Services. You are encouraged to frequently and carefully review these Terms to ensure that you understand these Terms.
           </Typography>

            <Typography variant="p">
                3. Privacy Policy: You acknowledge and confirm that you have read, understood, and agreed to provisions stipulated in the Website&apos;s Privacy Policy, which will explain how the Company treats your information and protects your privacy when accessing or using the Website.</Typography>

            <Typography variant="p">
                4. Links to and from the Website: You may, through hypertext or other computer links, gain access form the Website to websites operated or made available, or otherwise licensed by persons other than us (&quot;Third Party Services&quot;). Such hyperlinks are provided for your convenience. A link from Third Party Services does not mean that the Company endorses or approves the content on such website or does not mean that the Company is an operator of that website. You understand that you are solely responsible for determining the extent to which you may use or rely upon any content at any other Third Party Services websites which you have accessed from the Website. The Company has no control over the content of these sites or resources and accept no reasonability for them or for any loss or damage that may arise from your use of them. The Company assumes no responsibility for the use of, or inability to use, any Third Party Services&apos; software, other materials, or contents posted and/or uploaded on such website and we will have no liability whatsoever to any person or entity for any inaccuracy or incompleteness of such third-party content. All intellectual property rights in and to Third Party Services are property of the respective third parties.
            </Typography>

            <Typography variant="p">
                5. Disclaimer for Accessibility of the Website and the Services: 
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>1. The Website merely facilitates the Users accessibility to the Project tokens and does not provide you with any warranty or representation whatsoever regarding its quality, value, specification, fitness for the purpose, completeness or accuracy of its technology or infrastructure of the tokens.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>2. The Company will make all commercially reasonable attempts to facilitate information about the Project on the ErgoPad Website. However, you hereby acknowledge that the Company does not guarantee the accuracy, timeliness, or completeness of such information, and does not provide any warranty in connection with your use or reliance on such information. You agree that your use of the Project information will be at all your own risk. The Company will not be liable to you in any manner for the termination, interruption, delay, or inaccuracy of any Project information launched on the Ergo blockchain.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>3. To the extent permitted by applicable laws, the Website and the Company Services are provided on an &apos;AS IS&apos; and &apos;AS AVAILABLE&apos; basis. The Company does not warrant that the features, and functions contained in the Website and the Services will satisfy your preferences. You hereby agree and acknowledge that your access and use of the Website and the Services are at your own risk, and you will be liable for any responsibility, consequences that may arise out of or in connection with the usage or accessibility of the Website and the Services. You expressly agree that the Company will have absolutely no liability in this regard.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>4. You hereby agree and acknowledge that the Website may contain links to a third-party website or services that are not owned or even controlled by the Company, thus the Company will hold no responsibility for the content or services, goods, or activities provided by such third-party website. You further agree that the Company has no liability directly or indirectly for any damage, loss, or consequence arising out of or in connection with the usage or reliance of any content, material, services available through the third-party website.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>5. The Company reserves the right to limit the availability of the Website to any person, geographic area, or jurisdiction we so desire and/or terminate your access to and use of the Website and the Services, at any time and in our sole discretion.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>6. The Company may, at our sole discretion, impose limits or restrictions on the use you make of the Website. Further, for commercial, security, technical, maintenance, legal or regulatory reasons, or due to any breach of these Terms, we may withdraw the Website or your access to the Website and the Services at any time and without notice to You.
                </Typography>
                
            <Typography variant="p">6. Information: You acknowledge that you are solely responsible for any submissions of all contents, remarks, suggestions, ideas, materials, feedbacks, or other information, including bug reports in relation to the Services provided through the Website including any submission to our social media platforms such as Twitter and Telegram, and you, not us, have full responsibility for such submissions, including their accuracy, legality, reliability, appropriateness, originality, and copyright. We shall reply on the information you have provided and will not verify it. Notwithstanding the foregoing, we have the right to refuse to post, remove, edit, or abridge any submission for any reason and to freely use, copy, disclose, publish, display, or exploit such submission as we deem necessary without any payment of royalty, acknowledgement prior to consent, we may retain copies of all information materials relevant to the Service.
            </Typography>

            <Typography variant="h6">
                3. Participation in the ErgoPad Services
            </Typography>

            <Typography variant="p">
                1. Token Sales: The Company will provide access to smart contracts on the Platform through the Website that will enable Users to send Ergo in exchange for Ergopad Tokens and other Project Tokens. You accept that once these contracts are deployed on the Platform, we have no control or ability to alter their behavior. You accept full responsiblity for the outcome of any and all interacts with the Platform through the Website and agree to not seek indemity from the operators of the Website, or the Company, for any unexpected or undersireable outcomes while interacting with the Platform. The token is not considered a security of any kind, and does not carry any right of ownership of the Ergopad Platform. The Token is neither money nor legal tender/currency. 
            </Typography>

            <Typography variant="p">
                2. Staking: Users who stake ErgoPad Tokens through smart contracts will be eligible to participate in Projects launched on the ErgoPad Platform. The availability of Project tokens will be set on a case-by-case basis in smart contracts, and all details will be outlined on the Website. The operators of the Website will facilitate interaction with these smart contracts on the Ergo blockchain, but do not accept any legal liability for the bahavior of these smart contracts which are not deployed on the Website. You accept all liability and responsibility for any outcomes as a result of your interaction with these smart contracts through the use of this Website. 
            </Typography>

            <Typography variant="h6">
                4. Risk Disclosure
            </Typography>

            <Typography variant="p">
                By accessing the Website or using or participating in the Company Services, you expressly acknowledge and assume the following risks:
            </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>
                    1. Risk of loss in value: Tokens or any digital currencies are not issued by any central banks or national, supra-national, or quasi-national organizations. They are also not backed by any hard assets or other credit. The value of tokens or any digital currencies is affected by several factors, including but not limited to, the total number of tokens or any digital currencies in existence, the continued willingness of market participants to exchange government-issued currency for tokens or digital currencies , purchasers&apos; expectations with respect to the rate of inflation of fiat currencies, purchasers&apos; expectations with respect to the rate of deflation of cryptocurrencies, interest rates, currency exchange rates, cyber theft of cryptocurrencies from online digital wallet providers, or news of such theft from such providers or individuals&apos; digital wallets, investment and trading activities of large investors, monetary policies of the governments, trade restrictions, currency devaluations and revaluations, regulatory measures, the global or regional political, economic or financial events and situations. Thus, all these factors will affect the value of tokens or digital currencies, which may result in the permanent partial or total loss of the value of any particular token or digital currency. No one will be obliged to guarantee the liquidity or the market price of any ErgoPad tokens or digital currencies maintained in your Wallets. The volatility and unpredictability of the value of tokens or digital currencies relative to the government-issued currency may result in a significant loss over a short period of time.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>
                    2. The regulatory regime governing tokens or digital currencies: The regulatory framework relating to tokens or digital currencies remains unsettled, and any laws, regulations, or guidelines may be significantly revised and amended which will materially and adversely affect the value of any Tokens held, or a User&apos;s access to their Wallet or the Ergo blockchain. 
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>
                    3. Technical and system failure affecting the obligations stipulated in these Terms: the Website may experience system failures, and the Ergo blockchain and all associated smart contracts may experience unplanned interruptions, hardware or software defects, security breaches or other causes that could adversely affect the the Company infrastructure network, which includes the Website and ErgoPad Platform.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>
                    The Company is unable to anticipate the occurrence of hacks, cyber-attacks, mining attacks, including but not limited to double-spend attacks, majority mining power attacks and selfish-mining attacks, distributed denial of service attacks or errors, vulnerabilities or defects on the Website, ErgoPad Tokens, Users&apos; Wallets or any technology, including but not limited to smart contract technology. Also, the Company is unable to detect the hacks as mentioned earlier, mining attacks, cyber-attacks, distributed denials of service errors vulnerabilities, or defects in a timely manner and does not have sufficient resources to efficiently cope with multiple service incidents happening simultaneously or in rapid succession.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>
                    In addition, the Company&apos;s network or the services could be disrupted by numerous events, including natural disasters, equipment breakdown, network connectivity downtime, power losses, or even intentional disruptions of its services, such as disruptions caused by software viruses or attacks by unauthorized users, some of which are beyond the Company&apos;s control. Although the Company has taken steps and used its best endeavour against malicious attacks on its appliances or its infrastructure, which are critical for the maintenance of the ErgoPad Platform and the Services, there can be no assurance that cyber-attacks, such as distributed denials of the Service, will not be attempted in the future, and that the Company&apos;s enhanced security measures will be effective. Any significant breach of the Company&apos;s security measures or other disruptions resulting in a compromise of the usability, stability and security of the Company&apos;s network or the services, including the ErgoPad Platform, may adversely affect ErgoPad Tokens.
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>
                    4. You understand and agree that your use of the services and the website is completely at your own risk. This clause is not exhaustive and does not disclose all the risks associated with digital currencies and the use of services. Therefore, you are recommended to carefully consider whether such use is suitable for you in light of your judgement, circumstances, and financial position.
                </Typography>

            <Typography variant="h6">
                5. Limitation of Liability
            </Typography>

            <Typography variant="p">
                Notwithstanding any provisions within these terms, in no event will the company, its partners its affiliate, or its employees, agents, officers, or directors be liable to the user for any incidental, special, exemplary, punitive, indirect, or consequential damages of any kind, under any legal theory, arising out of or in connection with your use, or inability to use, the website, any websites linked to it, any content on the website or other such websites, or any other services or items obtained through the website, or other such websites, including, but not limited to, lost revenue, lost profits, loss of business or anticipated savings, loss of use, loss of goodwill, loss of data, loss of your credential information, loss or interruption of technology, loss of use of service or equipment, even if the user was advised of the possibility of such damages, and whether arising under a theory of contract, tort, strict liability or otherwise. The company will also have no liability for any emergency and/or unforeseeable incidents related to your use of the services on the ErgoPad platform such as stolen private key, or hacked accounts.
            </Typography>

            <Typography variant="h6">
                6. Indemnification
            </Typography>

            <Typography variant="p">
                You irrevocably undertake the responsibility of fully indemnifying and holding harmless each of the Company, its Affiliate, licensors, shareholders, officers, directors, managers, employees, and agents from and against any and all losses, claims, actions, proceedings, damages, demands, judgements, sums, liabilities, damages, costs, charges and expenses, including, but not limited to, any reasonable attorney&apos;s fees or penalties imposed by any regulatory authority, and reimbursements arising out of or related to the following situations:
            </Typography>

                <Typography variant="p" sx={{ ml: '3rem' }}>1. Your use or any person using the Services on your behalf or participation in accordance with the Services on the Website or the ErgoPad Platform;
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>2. Your breach of or our enforcement of these Terms;
                </Typography>
                <Typography variant="p" sx={{ ml: '3rem' }}>3. Any violations of Applicable Laws, regulation, or rights of any third-party during your use or participate in the Service.
                </Typography>

            <Typography variant="p">
                If you are obligated to indemnify the Company, its Affiliate, shareholders, licensors, officers, directors, managers, employees, and agents, the Company will have the right, at our sole discretion, to control any action or proceeding and to determine whether the Company wishes to proceed, or settle, and if so, on what terms or provisions.
            </Typography>


            <Typography variant="h6">
                7. No Financial and Legal Advice
            </Typography>

            <Typography variant="p">
                The Company is merely a technology platform, and is not your broker, intermediary, agent, or legal advisor and has no fiduciary relationship or obligation to you in connection with any decisions or activities effected by you using the Website or the Services. No communication or information provided to you by the Company is intended as or will be considered or construed as, the solicitation of an offer to buy, the investment advice, financial advice, legal advice, or any other sort of advice. All Services, transactions, and Investments will be executed automatically based on the parameters of your consideration. You will be solely responsible for determining whether any Services, or investments are suitable and match your interests according to your judgement, objectives, circumstances, and risk tolerance. You will be solely responsible for any losses or liabilities therefrom.
            </Typography>

            <Typography variant="p">
                Before executing any transactions, acquiring ErgoPad Tokens or IDO tokens on the ErgoPad Platform, you should consult with your independent financial, legal, or tax professionals. The Company and the operator of this Website will not be liable for the decisions you make to access and purchase through the Website.
            </Typography>

            <Typography variant="h6">
                8. Notice/Announcement
            </Typography>

            <Typography variant="p">
                Any notice, requests, demands, and determinations for the Company under these Terms (other than routine operational communications) shall be sent to support@ergopad.io
            </Typography>

            <Typography variant="h6">
                9. Governing Law, Dispute Resolution, Arbitration, and Lawsuits
            </Typography>

            <Typography variant="p">
                A DAO is not a traditional corporation, and as such is not registered under any government. A DAO involves a set of people interacting with each other according to a self-enforcing open-source protocol. Members of a DAO are not bound together by a legal entity, nor have they entered into any formal legal contracts. As such, the Company is steered by incentives tied to network tokens, and fully transparent rules that are written into the blockchain, which is enforced by machine consensus. 
            </Typography>

            <Typography variant="p">
                Therefore, any disputes regarding the outcome of the smart contracts in place on the Ergo blockchain are impossible to arbitrate. All the code is open source and visible to all, and the User accepts all responsibility for their interaction with said smart contracts. Your use of the Website to facilitate interaction with smart contracts on the Ergo blockchain is interpreted as acceptance of full personal liabliy. You will not hold the operator of the Website, the Company, its Affiliates, licensors, shareholders, officers, directors, managers, employees, or agents responsible for any perceived or tangible damages relating to your interaction with the blockchain. 
            </Typography>

        </Container>
    </>
  );
};

export default Terms;
